// Writes src/alignment.js. Used by import-alignment.mjs (from a forced-
// alignment run) and apply-timing.mjs (from the timing editor), so both
// produce the same file.

import { writeFile } from 'node:fs/promises';

// align: [[key, entry], ...] in song order; other: [{ t, t1, label }, ...]
export async function writeAlignment(file, align, other) {
  const body = align.map(([k, e]) => `  ${JSON.stringify(k)}: ${JSON.stringify(e)},`).join('\n');
  const rest = other.map(o => `  ${JSON.stringify(o)},`).join('\n');
  await writeFile(file, `// When each lyric line is actually sung, measured by forced alignment of the
// lyrics to the vocals: Whisper large-v3 (through stable-ts) and an MMS CTC
// aligner, each run on a separated vocal track and on the full mix, combined
// line by line. Generated by tools/import-alignment.mjs; corrected by ear in
// the timing editor (timing.html) and written back by tools/apply-timing.mjs.
//
// Keys are the sung text plus which occurrence it is. start/end are seconds;
// sylls are [start, end] for every syllable (a syllable can end before the
// next one starts); conf is high, medium or low; alt is the competing start
// when the aligners disagreed; unsure lists syllables they disagreed on by
// more than 0.5 s; checked marks a line corrected by ear.

export const ALIGN = {
${body}
};

// Singing that isn't a lyric line: vocalises, held notes, unidentified chant.
export const OTHER_SINGING = [
${rest}
];
`);
}
