// Downloads stroke-order data from KanjiVG for every Japanese character in
// the lyrics and writes src/strokes.js. Re-run after changing the lyrics.
//
//   node tools/fetch-strokes.mjs
//
// KanjiVG (https://kanjivg.tagaini.net) is by Ulrich Apel and contributors,
// licensed under CC BY-SA 3.0; the generated file carries the same licence.

import { writeFile } from 'node:fs/promises';
import { charset } from '../src/lyrics.js';

const BASE = 'https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/';

const out = {};
const missing = [];
for (const ch of charset('ja')) {
  const code = ch.codePointAt(0).toString(16).padStart(5, '0');
  const res = await fetch(`${BASE}${code}.svg`);
  if (!res.ok) { missing.push(ch); continue; }
  const svg = await res.text();
  // strokes are the paths with ids like kvg:08272-s3; order by that number
  const strokes = [...svg.matchAll(/<path[^>]*id="kvg:[0-9a-f]+-s(\d+)"[^>]*\sd="([^"]+)"/g)]
    .map(m => [+m[1], m[2]])
    .sort((a, b) => a[0] - b[0])
    .map(m => m[1]);
  if (strokes.length) out[ch] = strokes; else missing.push(ch);
}

const body = Object.entries(out).map(([ch, s]) => `  '${ch}': ${JSON.stringify(s)},`).join('\n');
await writeFile('src/strokes.js', `// Stroke order for the Japanese characters in the lyrics: one SVG path per
// stroke, in writing order, on KanjiVG's 109 x 109 grid.
// Generated by tools/fetch-strokes.mjs from KanjiVG (https://kanjivg.tagaini.net),
// copyright Ulrich Apel and contributors, CC BY-SA 3.0. This file is under the same licence.

export const STROKES = {
${body}
};
`);
console.log(`${Object.keys(out).length} characters written to src/strokes.js`);
if (missing.length) console.log(`no stroke data (will ink by flow instead): ${missing.join(' ')}`);
